function [fitresult, gof, h] = metricFitting(ax,xData, yData, grouping)
%CREATEFIT1(V1,VOLUMEFRACTION)
%  Create a fit.
%
%  Data for 'Linear Region' fit:
%      X Input : v1
%      Y Output: volumeFraction
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Sep-2021 14:44:15


%% Fit: 'Linear Region'.
[xData,yData] = prepareCurveData( xData, yData );

% Set up fittype and options.
pinchlims = zeros(length(grouping),2);
cdata = zeros(length(grouping),3);
for i = 1:length(grouping)
    switch grouping(i)
        case "Primitive"
            pinchlims(i,:) = [0.21, 0.79];
            glims = [-3 3];
            cdata(i,:) = [0 0 0.4];
        case "Diamond"
            pinchlims(i,:) = [0.11, 0.89];
            glims = [-sqrt(2) sqrt(2)];
            cdata(i,:) = [0 0.4 0];
        case "Gyroid"
            pinchlims(i,:) = [0.03, 0.97];
            glims = [-1.5 1.5];
            cdata(i,:) = [0.3 0 0];
%         case "Primitive"
%             pinchlims(i,:) = [0, 0.57];
%             glims = [0 3];
%             cdata(i,:) = [0 0 0.8];
%         case "Diamond"
%             pinchlims(i,:) = [0, 0.79];
%             glims = [0 sqrt(2)];
%             cdata(i,:) = [0 0.8 0];
%         case "Gyroid"
%             pinchlims(i,:) = [0, 0.94];
%             glims = [0 1.5];
%             cdata(i,:) = [0.8 0 0];
%         otherwise
%             pinchlims(i,:) = [0 1];
    end
end

ftname = 'A*x+B';
ft = fittype(ftname);
excludedPoints = (xData < pinchlims(:,1)) | (xData > pinchlims(:,2));
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
h = plot(fitresult, xData, yData, excludedPoints);


h(1).Color = [0 0 0];
h(2).Color = 'r';
h(3).Color = 'b';

% Label axes
ylabel('Isovalue v_1');
xlabel('Volume Fraction V^*');
axis(gca,[0 1 glims(1) glims(2)]);


verts = [0 glims(1); pinchlims(1,1) glims(1); pinchlims(1,1), glims(2); 0 glims(2);...
    1 glims(1); pinchlims(1,2) glims(1); pinchlims(1,2), glims(2); 1 glims(2)];
faces = [1 2 3 4; 5 6 7 8];


hold on
h(4) = patch(gca,'Faces',faces,'Vertices',verts,'FaceColor','r','FaceAlpha',0.2,'EdgeAlpha',0);

legend( h,'Data','Excluded Data',ftname ,'Pinch-Off Regions','Location', 'NorthWest');
grid on



